import { aiProvider } from './aiProvider.js';
import { parsePrompt } from './promptParser.js';
import { createPlan } from './planningAgent.js';
import { generateCode } from './codeGenerator.js';
import { debugAndRepair } from './debugAgent.js';
import { optimize } from './optimizer.js';
import pool from '../../config/db.js';

// Fallback HTML generator for when API fails
const generateFallbackHTML = (userPrompt, framework = 'html') => {
  const title = userPrompt.length > 60 ? userPrompt.substring(0, 60) : userPrompt;
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Poppins:wght@600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #333; }
        nav { background: rgba(0,0,0,0.7); padding: 1rem 2rem; color: white; display: flex; justify-content: space-between; align-items: center; }
        nav h1 { font-family: 'Poppins', sans-serif; font-size: 1.5rem; }
        nav a { color: white; text-decoration: none; margin-left: 2rem; transition: 0.3s; }
        nav a:hover { color: #667eea; }
        .hero { min-height: 100vh; display: flex; align-items: center; justify-content: center; text-align: center; color: white; padding: 2rem; }
        .hero h1 { font-family: 'Poppins', sans-serif; font-size: 3rem; margin-bottom: 1rem; }
        .hero p { font-size: 1.25rem; margin-bottom: 2rem; opacity: 0.9; }
        .btn { background: white; color: #667eea; padding: 1rem 2rem; border-radius: 8px; text-decoration: none; font-weight: 600; cursor: pointer; border: none; transition: 0.3s; display: inline-block; }
        .btn:hover { transform: translateY(-2px); box-shadow: 0 10px 20px rgba(0,0,0,0.2); }
        .features { padding: 4rem 2rem; background: white; display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 2rem; }
        .feature { padding: 2rem; border-radius: 8px; background: #f8f9fa; text-align: center; }
        .feature i { font-size: 2rem; color: #667eea; margin-bottom: 1rem; }
        .feature h3 { margin-bottom: 0.5rem; }
        footer { background: #1a1a1a; color: white; text-align: center; padding: 2rem; }
        @media (max-width: 768px) { .hero h1 { font-size: 2rem; } }
    </style>
</head>
<body>
    <nav>
        <h1>SiteForge</h1>
        <div>
            <a href="#home">Home</a>
            <a href="#features">Features</a>
            <a href="#contact">Contact</a>
        </div>
    </nav>
    <div class="hero">
        <div>
            <h1>${title}</h1>
            <p>Generated by SiteForge AI</p>
            <p style="font-size: 0.9rem; opacity: 0.8; margin-top: 2rem;">⚠️ The AI agent encountered an issue. This is a fallback template — try regenerating for a custom design.</p>
            <button class="btn" onclick="alert('Your custom content goes here!')">Get Started</button>
        </div>
    </div>
    <div class="features" id="features">
        <div class="feature">
            <i class="fas fa-bolt"></i>
            <h3>Fast</h3>
            <p>Lightning-quick performance optimized for all devices</p>
        </div>
        <div class="feature">
            <i class="fas fa-shield-alt"></i>
            <h3>Secure</h3>
            <p>Built with security best practices in mind</p>
        </div>
        <div class="feature">
            <i class="fas fa-mobile-alt"></i>
            <h3>Responsive</h3>
            <p>Perfect on desktop, tablet, and mobile</p>
        </div>
    </div>
    <footer id="contact">
        <p>&copy; 2026 SiteForge. Created with AI.</p>
    </footer>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            console.log('✅ Fallback page loaded');
        });
    </script>
</body>
</html>`;
};

export const runPipeline = async (userPrompt, framework = 'html', userId = null, projectId = null) => {
  const startTime = Date.now();
  let generationId = null;

  try {
    // Log generation start
    if (userId) {
      const genResult = await pool.query(
        'INSERT INTO ai_generations (user_id, project_id, prompt, framework, status) VALUES ($1, $2, $3, $4, $5) RETURNING id',
        [userId, projectId, userPrompt, framework, 'processing']
      );
      generationId = genResult.rows[0].id;
    }

    let finalCode;
    let parsedRequirements;
    let plan;
    let debugFixed = false;
    let debugIssues = [];

    try {
      // Agent 1: Parse Prompt
      console.log('🔍 Agent 1: Parsing prompt...');
      parsedRequirements = await parsePrompt(userPrompt, framework);

      // Agent 2: Create Plan
      console.log('📐 Agent 2: Creating plan...');
      plan = await createPlan(parsedRequirements, framework);

      // Agent 3: Generate Code
      console.log('⚡ Agent 3: Generating code...');
      const rawCode = await generateCode(plan, parsedRequirements, userPrompt, framework);

      // Agent 4: Debug & Repair
      console.log('🔧 Agent 4: Debugging...');
      const debugResult = await debugAndRepair(rawCode, plan);
      debugFixed = debugResult.fixed;
      debugIssues = debugResult.issues;

      // Agent 5: Optimize
      console.log('🚀 Agent 5: Optimizing...');
      finalCode = optimize(debugResult.code, plan);
    } catch (agentError) {
      console.error('[AI AGENT ERROR]', agentError.message);
      console.log('⚠️ Using fallback HTML generator...');
      finalCode = generateFallbackHTML(userPrompt, framework);
      parsedRequirements = parsedRequirements || {};
      plan = plan || {};
    }

    const duration = Date.now() - startTime;
    console.log(`✅ Pipeline complete in ${duration}ms`);

    // Update generation log
    if (generationId) {
      await pool.query(
        'UPDATE ai_generations SET status = $1, duration_ms = $2 WHERE id = $3',
        ['completed', duration, generationId]
      );
    }

    return {
      code: finalCode,
      plan,
      parsedRequirements,
      metadata: {
        duration,
        fixed: debugFixed,
        issues: debugIssues,
        framework,
        generationId,
      },
    };
  } catch (error) {
    const duration = Date.now() - startTime;
    if (generationId) {
      await pool.query(
        'UPDATE ai_generations SET status = $1, error_message = $2, duration_ms = $3 WHERE id = $4',
        ['failed', error.message, duration, generationId]
      );
    }
    throw error;
  }
};

// Improve existing design
export const improveDesign = async (existingCode, improvementPrompt, framework = 'html') => {
  const prompt = `You are an expert web designer. Improve the following website based on the user's feedback.
Return ONLY the complete improved HTML code.
NO markdown, NO code blocks. Start with <!DOCTYPE html>.

Current website code:
${existingCode.substring(0, 20000)}

User's improvement request: ${improvementPrompt}`;

  const result = await aiProvider.generate(prompt);
  let code = result.code;
  code = code.replace(/```html\n?/gi, '').replace(/```\n?/g, '').trim();

  return optimize(code, {});
};
