import archiver from 'archiver';
import { PassThrough } from 'stream';

/**
 * Generate a zip buffer from project data
 * @param {Object} project - Project data with html_code, title, framework
 * @param {Array} files - Additional project files [{file_path, file_content}]
 * @returns {Promise<Buffer>} Zip buffer
 */
export const generateZip = async (project, files = []) => {
  return new Promise((resolve, reject) => {
    const buffers = [];
    const converter = new PassThrough();
    const archive = archiver('zip', { zlib: { level: 9 } });

    converter.on('data', (chunk) => buffers.push(chunk));
    converter.on('end', () => resolve(Buffer.concat(buffers)));

    archive.on('error', reject);
    archive.pipe(converter);

    const projectName = (project.title || 'website').replace(/[^a-zA-Z0-9-_]/g, '-').substring(0, 50);

    // Main HTML file
    if (project.html_code) {
      archive.append(project.html_code, { name: `${projectName}/index.html` });
    }

    // Additional project files
    if (files.length > 0) {
      files.forEach((file) => {
        archive.append(file.file_content || '', { name: `${projectName}/${file.file_path}` });
      });
    }

    // README
    const readme = `# ${project.title || 'Generated Website'}

Generated by SiteForge AI on ${new Date().toLocaleDateString()}

## Prompt
${project.prompt || 'N/A'}

## Framework
${project.framework || 'HTML/CSS/JS'}

## How to Use
1. Open \`index.html\` in your browser
2. Edit the code as needed
3. Deploy to any static hosting (Netlify, Vercel, GitHub Pages)

## Credits
Built with [SiteForge AI](https://siteforge.ai) — AI Website Builder
`;
    archive.append(readme, { name: `${projectName}/README.md` });

    // package.json for React/Next projects
    if (project.framework === 'react' || project.framework === 'nextjs') {
      const pkg = {
        name: projectName,
        version: '1.0.0',
        description: project.title || 'Generated website',
        scripts: { start: 'npx serve .' },
      };
      archive.append(JSON.stringify(pkg, null, 2), { name: `${projectName}/package.json` });
    }

    archive.finalize();
  });
};
